// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const databaseUrl = process.env["DATABASE_URL"]?.trim();
const directUrl = process.env["DIRECT_URL"]?.trim();
const postgresUrl = process.env["DATABASE_URL_POSTGRES"]?.trim();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/postgres-migrations",
  },
  datasource: {
    url: directUrl
      ? directUrl
      : databaseUrl && !databaseUrl.startsWith("file:")
        ? databaseUrl
        : postgresUrl,
  },
});
